name: 你凭什么有 bug
description: 谁让你有 bug 的
body:
  - type: checkboxes
    id: checks
    attributes:
      options:
        - label: 我没有 bug
          required: true
  - type: textarea
    id: huh
    attributes:
      label: 你真有 bug？
      description: 有 bug 也不许写
    validations:
      required: false
