name: 你凭什么有 bug
description: 谁让你有 bug 的
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 你有 bug 吗？
      options:
        - label: 我没有 bug
          required: true
        - label: 我真没有 bug
          required: true
  - type: textarea
    id: describe
    attributes:
      label: 你真有 bug ？
      description: 描述 bug 时请尽量不要描述 bug
    validations:
      required: true
